version: '3.7'

services:
  hello-world:
    image: microsoft/iis
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.httpsOnly=true
        - com.df.serviceDomain.1=hello-world.swarm.usc.edu
        - com.df.port.1=80
        - com.df.serviceDomain.2=helloworld.swarm.usc.edu
        - com.df.port.2=80
networks:
  proxy:
    external: true
