version: "3.7"

services:
  sonarqube:
    image: sonarqube:${SONARQUBE_TAG:-latest}
    ports:
    - "9000:9000"
    networks:
    - proxy
    - docker-proxy
    - sonarnet
    environment:
    - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=9000
        - com.df.httpsOnly=true
        - com.df.serviceDomain=sonarqube.${DOMAIN_NAME:-docker.usc.edu}

  db:
    image: postgres:${SONARQUBE_POSTGRES_TAG:-latest}
    networks:
    - sonarnet
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    volumes:
    - postgresql:/var/lib/postgresql
    # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
    - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: overlay
  proxy:
    external: true
  docker-proxy:
    external: true

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data: