version: '3.1'
services:
  mobile-wordpress:
    image: wordpress
    ports:
      - ${USC_MOBILE_PORT}:80
    depends_on:
      - mobile-db
    networks:
      proxy:
      mobile-db:
    volumes:
      - mobile-data:/var/www/html
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      - WORDPRESS_DB_PASSWORD=${USC_MOBILE_DB_PASSWORD}
      - WORDPRESS_DB_HOST=mobile-db
      - ServerName=${USC_MOBILE_SERVER_NAME}
  mobile-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${USC_MOBILE_DB_PASSWORD}
    networks:
      mobile-db:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname==${NODE01}
    volumes:
      - mobile-db:/var/lib/mysql
networks:
  proxy:
    external:
      name: proxy
  mobile-db:
#    driver: overlay
    external:
      name: mobile-db
volumes:
  mobile-db:
    external:
      name: mobile-db
  mobile-data:
    external:
      name: mobile-data
