version: '3'
services:

  falco:
    image: falcosecurity/falco
#    privileged: true
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /host/dev:/dev
      - /host/proc:/proc:ro
      - /host/boot:/boot:ro
      - /host/lib/modules:/lib/modules:ro
      - /host/usr:/usr:ro
    networks:
      - logging
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - security.monitor=falco

networks:
  logging:
    external: true