version: '3.7'
services:

  wordpress-selenium-test:
       image: uscdev/wordpress-selenium-test
       networks:
#       - seleniumhub
       - proxy
       deploy:
         replicas: 1
         update_config:
           parallelism: 1
           delay: 10s
         restart_policy:
           condition: none

networks:
  seleniumhub:
    external: true
  proxy:
    external: true
