version: '3.2'

services:
  helloworld:
    image: tutum/hello-world
    networks:
      - proxy
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=hello-world.swarm.usc.edu
        - com.df.port=80
        - com.df.httpsOnly=true
networks:
  proxy:
    external: true
