version: '3.7'

services:
  hello-world:
    image: tutum/hello-world:${HELLO_WORLD_TAG:-latest}
    networks:
      - proxy
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.httpsOnly=true
        - com.df.serviceDomain.1=hello-world.${DOMAIN_NAME:-docker.usc.edu}
        - com.df.port.1=80
        - com.df.serviceDomain.2=helloworld.${DOMAIN_NAME:-docker.usc.edu}
        - com.df.port.2=80
networks:
  proxy:
    external: true
