version: '3.5'
services:
  nginx-dtr:
    image: uscdev/nginx-dtr:swarm-1.0.0
#    ports:
#      - 8443:8443
    networks:
      - proxy
    secrets:
      - swarm.usc.edu.key
      - swarm.usc.edu.cer
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.httpsOnly=true
        - com.df.port=8442
        - com.df.serviceDomain=dtr.${DOMAIN_NAME:-docker.usc.edu}
        - com.df.sslVerifyNone=true
networks:
  proxy:
    external: true
secrets:
  swarm.usc.edu.key:
    external: true
  swarm.usc.edu.cer:
    external: true
