version: '3.5'
services:
  nginx:
    image: nginx
    ports:
      - 8443:80
    networks:
      - proxy
    volumes:
      - nginx-data:/usr/share/nginx/html
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=nginx.poc.usc.edu
        - com.df.port=80
        - com.df.httpsOnly=true
      placement:
        constraints:
          - node.hostname==${NODE00}
networks:
  proxy:
    external: true
volumes:
  nginx-data:
