version: "3.1"

services:

  proxy:
    image: uscdev/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 1
    secrets:
      - cert-swarm.usc.edu.pem
#      - cert-emailchoice.usc.edu.pem
#      - cert-workday-account-translator.usc.edu.pem

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external:
      name: proxy
secrets:
  cert-swarm.usc.edu.pem:
    external: true
  cert-emailchoice.usc.edu.pem:
    external: true
  cert-workday-account-translator.usc.edu.pem:
    external: true
