version: "3.7"

services:

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
    - default
    environment:
    - NODE_ID={{.Node.ID}}
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    - /etc/hostname:/etc/nodename
    command:
    - '--path.sysfs=/host/sys'
    - '--path.procfs=/host/proc'
    - '--collector.textfile.directory=/etc/node-exporter/'
    - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    # no collectors are explicitely enabled here, because the defaults are just fine,
    # see https://github.com/prometheus/node_exporter
    # disable ipvs collector because it barfs the node-exporter logs full with errors on my centos 7 vm's
    - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  cadvisor:
    image: google/cadvisor
    networks:
    - default
    command: -logtostderr -docker_only
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /:/rootfs:ro
    - /var/run:/var/run
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: vfarcic/prometheus-devops21
    networks:
    - default
    - proxy
    ports:
    - 9091:9090
    deploy:
      labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.port=9090
      - com.df.httpsOnly=true
      - com.df.serviceDomain=prometheus.docker.usc.edu
      - com.df.xForwardedProto=true
      mode: replicated
      replicas: 1

  grafana:
    image: stefanprodan/swarmprom-grafana:5.0.1
    networks:
    - default
    - proxy
    environment:
    - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
    - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    - GF_USERS_ALLOW_SIGN_UP=false
#    - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
    #- GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-localhost}
    #- GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}
    #- GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-grafana@test.com}
    #- GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}
    #- GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}
    #- GF_SMTP_USER=${GF_SMTP_USER}
    #- GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    volumes:
    - grafana:/var/lib/grafana
    deploy:
      labels:
      - com.df.notify=true
      - com.df.distribute=true
#     - com.df.servicePath=/grafana/,/grafana/public,/grafana/api
#      - com.df.reqPathSearch=/grafana/
#      - com.df.reqPathReplace=/
      - com.df.port=3000
#      - com.df.httpsOnly=true
      - com.df.serviceDomain=grafana.docker.usc.edu
      - com.df.xForwardedProto=true
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

networks:
  default:
    external: false
  logging_default:
    external: true
  proxy:
    external: true

volumes:
  prometheus: {}
  grafana: {}
  alertmanager: {}
