version: "3.7"
services:

  selenium:
    image: selenium/hub
    hostname: selenium
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 4444" /usr/bin/supervisord --configuration /etc/supervisord.conf'
    networks:
    - guacamole # No - use selenium-nodes
#    - selenium-nodes
#    - selenium
    - test
    - proxy
    ports:
    - "4444:4444"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  chrome:
    image: selenium/node-chrome-debug
    hostname: chrome
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 4444" /usr/bin/supervisord --configuration /etc/supervisord.conf'
    depends_on:
    - selenium
    ports:
    - "5556:5555"
    - "5901:5900"
    environment:
    - HUB_HOST=selenium
    - HUB_PORT=4444
    - NODE_MAX_SESSION=1
#    shm_size: "2g"
    volumes:
    - /dev/shm:/dev/shm
    networks:
#    - selenium-nodes
    - guacamole
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  firefox:
    image: selenium/node-firefox-debug
    hostname: firefox
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 4444" /usr/bin/supervisord --configuration /etc/supervisord.conf'
    depends_on:
    - selenium
    ports:
    - "5557:5555"
    - "5902:5900"
    environment:
    - HUB_HOST=selenium
    - HUB_PORT=4444
    - NODE_MAX_SESSION=1
    #    shm_size: "2g"
    volumes:
    - /dev/shm:/dev/shm
    networks:
#    - selenium-nodes
    - guacamole
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  selenium-nodes:
    driver: overlay
  selenium:
    external: true
  guacamole:
    external: true
  proxy:
    external: true
  test:
    external: true
