version: "3.7"
services:

  seleniumhub:
    image: selenium/hub
    networks:
    - seleniumhub
    - selenium
    ports:
    - "4444:4444"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
    - seleniumhub
    ports:
    - "5556:5555"
    - "5901:5900"
    environment:
    - HUB_HOST=seleniumhub
    - HUB_PORT=4444
    networks:
    - seleniumhub
    - proxy
    - guacamole
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  firefox:
    image: selenium/node-firefox-debug
    depends_on:
    - seleniumhub
    ports:
    - "5557:5555"
    - "5902:5900"
    environment:
    - HUB_HOST=seleniumhub
    - HUB_PORT=4444
    networks:
    - seleniumhub
    - proxy
    - guacamole
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  selenium:
    driver: overlay
  seleniumhub:
    external: true
  guacamole:
    external: true
  proxy:
    external: true
