version: "3.7"
services:

  seleniumhub:
    image: selenium/hub
    networks:
    - proxy
#    - seleniumhub
#    - selenium
    ports:
    - "4444:4444"
    hostname: seleniumhub
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
    - seleniumhub
    ports:
    - "5556:5555"
    - "5901:5900"
    environment:
    - HUB_HOST=seleniumhub
    - HUB_PORT=4444
    - NODE_MAX_SESSION=1
    hostname: chrome
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
#    - --shm-size=2g
#    volumes:
#    - /dev/shm:/dev/shm
    networks:
#    - seleniumhub
    - proxy
#    - guacamole
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  firefox:
    image: selenium/node-firefox-debug
    depends_on:
    - seleniumhub
    ports:
    - "5557:5555"
    - "5902:5900"
    environment:
    - HUB_HOST=seleniumhub
    - HUB_PORT=4444
    - NODE_MAX_SESSION=1
    hostname: firefox
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    networks:
#    - seleniumhub
    - proxy
#    - guacamole
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  selenium:
    driver: overlay
  seleniumhub:
    external: true
  guacamole:
    external: true
  proxy:
    external: true
